# Generated by Django 5.1.8 on 2025-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('partner', 'Partner'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
